input.onButtonPressed(Button.A, function () {
    music.playTone(131, music.beat(BeatFraction.Whole))
    music.playTone(139, music.beat(BeatFraction.Whole))
    music.playTone(147, music.beat(BeatFraction.Whole))
    music.playTone(156, music.beat(BeatFraction.Whole))
    music.playTone(165, music.beat(BeatFraction.Whole))
    music.playTone(175, music.beat(BeatFraction.Whole))
    music.playTone(185, music.beat(BeatFraction.Whole))
    music.playTone(392, music.beat(BeatFraction.Whole))
    music.playTone(415, music.beat(BeatFraction.Whole))
    music.playTone(440, music.beat(BeatFraction.Whole))
    music.playTone(466, music.beat(BeatFraction.Whole))
    music.playTone(494, music.beat(BeatFraction.Whole))
    music.playTone(523, music.beat(BeatFraction.Whole))
    music.playTone(554, music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Whole))
    music.playTone(622, music.beat(BeatFraction.Whole))
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(698, music.beat(BeatFraction.Whole))
    music.playTone(740, music.beat(BeatFraction.Whole))
    music.playTone(784, music.beat(BeatFraction.Whole))
    music.playTone(831, music.beat(BeatFraction.Whole))
    music.playTone(880, music.beat(BeatFraction.Whole))
    music.playTone(932, music.beat(BeatFraction.Whole))
    music.playTone(988, music.beat(BeatFraction.Whole))
})
input.onButtonPressed(Button.B, function () {
    music.playMelody("C5 B A G F E D C ", 120)
    basic.pause(100)
    music.playMelody("C D E F G A B C5 ", 120)
    basic.pause(100)
    music.playMelody("E B C5 A B G A F ", 120)
    basic.pause(100)
    music.playMelody("A F E F D G E F ", 120)
    basic.pause(100)
    music.playMelody("C5 A B G A F G E ", 120)
    basic.pause(100)
    music.playMelody("G B A G C5 B A B ", 120)
    basic.pause(100)
    music.playMelody("B A G A G F A C5 ", 120)
    basic.pause(100)
    music.playMelody("G F G A - F E D ", 120)
    basic.pause(100)
    music.playMelody("E D G F B A C5 B ", 120)
    basic.pause(100)
    music.playMelody("C5 G B A F A C5 B ", 120)
    basic.pause(100)
})
music.setVolume(255)
basic.forever(function () {
	
})
